### ISSUE TITLE
Promote reactive integrations to stable API

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.coroutines#2545]

**Comment by dkhalanskyjb** [comment]
An overview of the current problems:

- [ ] Various incompatibilities with the [Reactive Streams spec](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md)
  - [ ] `publish { }` permits emitting nullable values: https://github.com/Kotlin/kotlinx.coroutines/pull/2617/commits/099d2bef6d81a9990f067bae75af0d2ca977604c 
  - [ ] `reactorPublish { }` throws when given something other than `CorePublisher`: https://github.com/Kotlin/kotlinx.coroutines/pull/2622/commits/24ce99d895f401de0af41291928affbe662ab264 maybe not a problem, since currently Reactor always passes a `CorePublisher`?
  - [ ] `reactorPublish { }` and `mono { }` permit emitting nullable values (Reactor docs explicitly say that [nulls are not supported](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#mapNotNull-java.util.function.Function-))
  - [ ] `ReactiveSubscriber` throws in `onNext` if the channel is full
- [ ] Doc improvements (https://github.com/Kotlin/kotlinx.coroutines/pull/2622/commits/b60872b7c073fa61d5aad1afc94bb432d0276fc7, https://github.com/Kotlin/kotlinx.coroutines/pull/2617/commits/1e4b4cb84318a5f87d2a1b67021ed151821253ae, and further fixes needed):
  - [ ] Some docs don't describe error handling sufficiently
  - [ ] Wrong references or lack of references
- [ ] Missing useful methods
  - [ ] `awaitSingleOr*` in the JDK9 Flow integration (https://github.com/Kotlin/kotlinx.coroutines/pull/2617/commits/9b210e42fcbb0eba824bd165c7a5bd8548fff426)
  - [ ] `await` on Reactor's Mono (https://github.com/Kotlin/kotlinx.coroutines/issues/1587)
- [ ] Bugs:
  - [ ] `awaitSingleOrNull` is broken (https://github.com/Kotlin/kotlinx.coroutines/issues/2591, https://github.com/Kotlin/kotlinx.coroutines/pull/2617/commits/b9099d05952513e5a25421869a0cd16421b813fd)
  - [ ] `mono` ignores cancellations (https://github.com/Kotlin/kotlinx.coroutines/issues/2262, fixed in https://github.com/Kotlin/kotlinx.coroutines/pull/2606)
  - [ ] Building a `CoroutineContext` element from Reactor's `ContextView` (https://github.com/Kotlin/kotlinx.coroutines/issues/2575, https://github.com/Kotlin/kotlinx.coroutines/pull/2622/commits/de2b4f4225df708f35ea0b39d55fc94cb60bc9ee)
- [ ] Error handling issues
  - [ ] Handling fatal exceptions in RxJava (https://github.com/Kotlin/kotlinx.coroutines/issues/2173) The root cause for the problem is https://github.com/ReactiveX/RxJava/issues/7217, with RxJava's position being that the users must make sure not to allow fatal exceptions to propagate to the Rx machinery.
- [ ] Dispatching
  - [ ] Suboptimal execution context guarantees (https://github.com/Kotlin/kotlinx.coroutines/issues/2485): when subscribing to a publisher in an RxJava or Reactor chain, the chain itself may impose restrictions on where execution should happen (with `observeOn()` and such), but we ignore that and launch the coroutines in the default dispatcher. Maybe open an event loop on the provided threads instead?
  - [ ] Using a `CoroutineDispatcher` as an RxJava `Scheduler` (https://github.com/Kotlin/kotlinx.coroutines/issues/968, https://github.com/Kotlin/kotlinx.coroutines/issues/548, with a PR in progress https://github.com/Kotlin/kotlinx.coroutines/pull/1923)
