### ISSUE TITLE
Kotlin 1.9.20 update tracking issue

### ISSUE THREAD

**Issue by nikitabobko** [Kotlin/kotlinx.coroutines#3846]
- [x] #3828
- [x] Fix all `3846` references in the code base (e.g. #3847)
- [x] Update kotlin/wasm targets in buildscripts - remove all 1.9.0 related code marked with `3846` references
- [x] https://github.com/Kotlin/kotlinx.coroutines/pull/3891/files

**Comment by qwwdfsad** [comment]
Fixed with #3926
